
POST http://localhost:8000/device HTTP/1.1
Content-Type:  application/json

{
    "token" : "dPokZZonTj-TgjyESCcnF8:APA91bGMzmPsglPnegn7y_XZTpEbIK6FgxHG2PwdEJJIWb7vsh9G8vdHXGyEMZ8O9KpyIt0mIB9ryT6f3zTHtMRxtQM9pe49hHIZRrXaSLcMaAdyOA04PHeRuFzXrzPOi0HwtkxWnb-d",
	"monitorID" : "2d52b55c-247f-4ff2-a75c-828c35c6f63d"
}

###
POST   http://localhost:8000/device/send-notification HTTP/1.1
Content-Type:  application/json

{
    "monitorID" : "36ba0421-9679-4068-b119-2d0dcfc0b0a9"
}

###
GET    http://localhost:8000/device/9744bdc1-106a-471f-aa41-3e78b338ab31 HTTP/1.1
Content-Type:  application/json
