POST http://localhost:8000/driver HTTP/1.1
Content-Type:  application/json

{
    "cpf":"",
	"name":"algum_motorista",
	"nickname":"moto",
	"phone":"11 977345433",
    "uf":"sp",
	"city":"sumare",
	"street":"rua parana",
	"number":"123",
	"cep":"13233309"
}

###  BUSCAR TODOS MOTORISTAS
GET  http://localhost:8000/driver HTTP/1.1
Content-Type:  application/json


### BUSCAR POR ID
GET  http://localhost:8000/driver/tfy HTTP/1.1
Content-Type:  application/json


###
PUT   http://localhost:8000/driver HTTP/1.1
Content-Type:  application/json

{
	"id": "1d33ff03-d8a1-4c8a-9fb6-ecdac4943c57",
    "cpf":"23453235345",
	"name":"Joao",
	"nickname":"motô",
	"phone":"11 977345433",
    "uf":"sp",
	"city":"Jundiai",
	"street":"rua parana",
	"number":"123",
	"cep":"13233309"
}

###
DELETE    http://localhost:8000/driver/4941f886-9685-4d49-868e-8e93bf574cb3 HTTP/1.1
Content-Type:  application/json
