
POST http://localhost:8000/driver HTTP/1.1
Content-Type:  application/json

{
    "cpf":"11111111111",
	"name":"Lurdes",
	"nickname":"tia lu",
	"phone":"11 977345433",
    "uf":"MG",
	"city":"lagos",
	"street":"tres corregos",
	"number":"123",
	"cep":"13233309"
}

###  BUSCAR TODOS MOTORISTAS
GET  http://localhost:8000/driver HTTP/1.1
Content-Type:  application/json

### BUSCAR POR ID
GET  http://localhost:8000/driver/a37c14e7-af25-49ce-bf7f-d19ea48c051e HTTP/1.1
Content-Type:  application/json

### ATUALIZAR DADOS DO MOTORISTA
PUT   http://localhost:8000/driver HTTP/1.1
Content-Type:  application/json

{
	"id": "a37c14e7-af25-49ce-bf7f-d19ea48c051e",
    "cpf":"23453235345",
	"name":"Joao",
	"nickname":"motô",
	"phone":"11 977345433",
    "uf":"sp",
	"city":"Jundiai",
	"street":"rua parana",
	"number":"123",
	"cep":"13233309"
}

###

DELETE    http://localhost:8000/driver/2d763fea-29fe-4ed0-a898-ebf73fce4343 HTTP/1.1
Content-Type:  application/json


### CHANGE LOCALIZACAO ATUAL
POST http://localhost:8000/driver/location HTTP/1.1

{
	"route_code": "40538901832d",
	"latitude": "-22.96329690239083",
	"longitude": "-46.997982015276186"
}


### CRIAR ROTA
POST http://localhost:8000/driver/route HTTP/1.1

{
	"name": "sesi 386",
	"driver_id": "3b64a7aa-80d4-4c20-9c63-8873012ab63c"
}
