### CHANGE LOCALIZACAO ATUAL
POST http://localhost:8000/driver/location HTTP/1.1
Content-Type:  application/json

{
	"route_code": "aef88e44426a",
	"latitude": "-22.96329690239083",
	"longitude": "-46.997982015276186"
}