POST http://localhost:8000/monitor HTTP/1.1
Content-Type:  application/json

{
    "name":        	"monitor",
	"cpf":         	"11111111111",
	"phone_number": "21212121121",
    "uf":			"MG",
	"city":			"BH",
	"street":		"rua lagoinha",
	"number":		"6565",
	"cep":			"13233309"
}

###  BUSCAR TODOS MONITORES
GET  http://localhost:8000/monitor HTTP/1.1
Content-Type:  application/json


### BUSCAR POR ID
GET  http://localhost:8000/monitor/eea70d27-c9e8-43e8-8830-dab5b3b75654 HTTP/1.1
Content-Type:  application/json


### ATUALIZAR DADOS DO MONITORES
PUT   http://localhost:8000/monitor HTTP/1.1
Content-Type:  application/json

{
	"id": 			"eea70d27-c9e8-43e8-8830-dab5b3b75654",
    "name":        	"O cara que vai ficar vendo as rotas",
	"cpf":         	"22222222222",
	"phone_number": "76767676767",
    "uf":			"MG",
	"city":			"Belo Horizonte",
	"street":		"Rua lagoinha",
	"number":		"6565",
	"cep":			"13233309"
}

###
DELETE    http://localhost:8000/monitor/eea70d27-c9e8-43e8-8830-dab5b3b75654 HTTP/1.1
Content-Type:  application/json
