
POST http://localhost:8000/monitor HTTP/1.1
Content-Type:  application/json

{
    "name":        	"monitor",
	"cpf":         	"2323232323",
	"phone_number": "21212121121",
    "uf":			"MG",
	"city":			"BH",
	"street":		"rua lagoinha",
	"number":		"6565",
	"cep":			"13233309"
}

###  BUSCAR TODOS MONITORES
GET  http://localhost:8000/monitor HTTP/1.1
Content-Type:  application/json


### BUSCAR POR ID
GET  http://localhost:8000/monitor/6a6b2b14-345e-4e09-9a9e-0e72871094ce HTTP/1.1
Content-Type:  application/json


### ATUALIZAR DADOS DO MONITORES
PUT   http://localhost:8000/monitor HTTP/1.1
Content-Type:  application/json

{
	"id": 			"3017aae8-572f-4482-ad36-5c3db9946185",
    "name":        	"O cara que vai ficar vendo as rotas",
	"cpf":         	"22222222222",
	"phone_number": "76767676767",
    "uf":			"MG",
	"city":			"Belo Horizonte",
	"street":		"Rua lagoinha",
	"number":		"6565",
	"cep":			"13233309"
}

###
DELETE    http://localhost:8000/monitor/3017aae8-572f-4482-ad36-5c3db9946185 HTTP/1.1
Content-Type:  application/json

###
GET  http://localhost:8000/monitor/location/route_code HTTP/1.1
Content-Type:  application/json
