###  AUTENTICATE
GET  http://localhost:8000/monitor/auth/authenticate/11111111111 HTTP/1.1
Content-Type:  application/json


###

POST http://localhost:8000/monitor HTTP/1.1
Content-Type:  application/json

{
    "name":        	"monitor2",
	"cpf":         	"11111111111",
	"phone_number": "21212121121",
    "uf":			"MG",
	"city":			"BH",
	"street":		"rua lagoinha",
	"number":		"6565",
	"cep":			"13233309"
}

###  BUSCAR TODOS MONITORES
GET  http://localhost:8000/monitor HTTP/1.1
Content-Type:  application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzkxMTI4NjV9.ykJXYRI5USgyU4S9-oqmt7E8_Ou-W7YkZVapIamWWDA


### BUSCAR POR ID
GET  http://localhost:8000/monitor/85f14b3c-9b4d-4bda-97c7-84688e472a6f HTTP/1.1
Content-Type:  application/json

### ATUALIZAR DADOS DO MONITORES
PUT   http://localhost:8000/monitor HTTP/1.1
Content-Type:  application/json

{
	"id": 			"31ad6529-0970-44da-8329-fa54c38c4f50",
    "name":        	"O cara que vai ficar vendo as rotas",
	"cpf":         	"22222222222",
	"phone_number": "76767676767",
    "uf":			"MG",
	"city":			"Belo Horizonte",
	"street":		"Rua lagoinha",
	"number":		"6565",
	"cep":			"13233309"
}

###

DELETE    http://localhost:8000/monitor/06aafaeb-a5a1-4a49-b832-96eb54d54c60 HTTP/1.1
Content-Type:  application/json

###
GET  http://localhost:8000/monitor/location/route_code HTTP/1.1
Content-Type:  application/json


###  BUSCAR PASSAGEIROS API
GET  http://localhost:8000/passenger/list-passenger/85f14b3c-9b4d-4bda-97c7-84688e472a6f HTTP/1.1
Content-Type:  application/json


###  PEGA MOTORISTA PELO CODIGO DA ROTA
GET  http://localhost:8000/monitor/getdriver-by-route/8b58055b-9671-41a9-9fb0-3f61818a10e0 HTTP/1.1
Content-Type:  application/json
