
GET  http://localhost:8000/partner HTTP/1.1
Content-Type:  application/json


###
POST http://localhost:8000/partner HTTP/1.1
Content-Type:  application/json

{
	"name":      	"Lava car",
	"description": 	"especializada em vans",
	"price":	  	100.0,
	"phone_number": "76767676767",
    "uf":			"MG",
	"city":			"Belo Horizonte",
	"street":		"Rua lagoinha",
	"number":		"6565",
	"cep":			"13233309",
	"latitude": 	"-22.96329690239083",
	"longitude": 	"-46.997982015276186"
}


###
GET  http://localhost:8000/partner/209b31f0-dce9-4405-ab59-c7844b7f91b5 HTTP/1.1
Content-Type:  application/json


###
PUT   http://localhost:8000/partner HTTP/1.1
Content-Type:  application/json

{
	"id":			"c43bb69e-17c5-477e-ad3c-bad97d927831",
	"name":      	"Lava car",
	"description": 	"Updated",
	"price":	  	70.0,
	"phone_number": "76767676767",
    "uf":			"MG",
	"city":			"Belo Horizonte",
	"street":		"Rua lagoinha",
	"number":		"6565",
	"cep":			"13233309",
	"latitude": 	"-22.96329690239083",
	"longitude": 	"-46.997982015276186"
}


###
DELETE    http://localhost:8000/partner/dc9a4a02-a56a-4d7f-b6d6-ecec0ccfff36 HTTP/1.1
Content-Type:  application/json
