
POST http://localhost:8000/passenger HTTP/1.1
Content-Type:  application/json

{
    "name" : "rodolfo",
	"nickname" : "ro",
	"routeCode" : "c356e41eb202",
	"schoolName": "SESI 286 - noite",
	"monitorID" : "683d0bae-4767-456c-be48-439531ffae9f"
}

###  BUSCAR TODOS PASSAGEIROS
GET  http://localhost:8000/passenger HTTP/1.1
Content-Type:  application/json

### BUSCAR POR ID
GET  http://localhost:8000/passenger/209b31f0-dce9-4405-ab59-c7844b7f91b5 HTTP/1.1
Content-Type:  application/json


### ATUALIZAR DADOS DO PASSAGEIROS
PUT   http://localhost:8000/passenger HTTP/1.1
Content-Type:  application/json

{
	"id": "07a95aa0-552f-474e-9190-6045e66a6bc7",
	"name" : "GUILHERME",
	"nickname" : "GUI",
	"routeCode" : "3847a582889e",
	"schoolName": "SESI 777",
	"goes":false,
	"comesback": false,
	"registerConfirmed": true,
	"monitorID": "d1b68cef-478c-43bb-a1e2-c1155305775f"
}

###

DELETE    http://localhost:8000/passenger/d7319148-5b13-49c1-a8c5-aa50856d503f HTTP/1.1
Content-Type:  application/json

### CONFIRMAR REGISTRO DO PASSAGEIRO
PUT   http://localhost:8000/passenger/confirm-passenger HTTP/1.1
Content-Type:  application/json

{
	"passengerID": 		"3204aa1c-08a9-454d-b6d9-25e4cd69de98",
    "registerConfirmed":	false
}


###
POST  http://localhost:8000/passenger/finalize-route HTTP/1.1
Content-Type:  application/json


###
GET  http://localhost:8000/passenger/not-confirmed/0397fe937858 HTTP/1.1
Content-Type:  application/json