
POST http://localhost:8000/passenger HTTP/1.1
Content-Type:  application/json

{
    "name" : "any_name",
	"nickname" : "any_nickname",
	"route_code" : "any_route_code",
	"monitor_id" : "5c39847f-3005-4fc5-8e88-217f817ce7e5"
}

###  BUSCAR TODOS PASSAGEIROS
GET  http://localhost:8000/passenger HTTP/1.1
Content-Type:  application/json

### BUSCAR POR ID
GET  http://localhost:8000/passenger/1062768d-689d-421f-a04b-a983d91b9c03 HTTP/1.1
Content-Type:  application/json


### ATUALIZAR DADOS DO PASSAGEIROS
PUT   http://localhost:8000/passenger HTTP/1.1
Content-Type:  application/json

{
	"id": "df25c902-1381-4615-809b-d9a30cd60bc7",
	"name" : "other_name",
	"nickname" : "other_nickname",
	"route_code" : "other_route_code",
	"monitor_id": "5c39847f-3005-4fc5-8e88-217f817ce7e5"
}

###
DELETE    http://localhost:8000/passenger/df25c902-1381-4615-809b-d9a30cd60bc7 HTTP/1.1
Content-Type:  application/json

### ATUALIZAR DADOS DO MOTORISTA
PUT   http://localhost:8000/passenger/confirm-passenger HTTP/1.1
Content-Type:  application/json

{
	"passenger_id": 		"1062768d-689d-421f-a04b-a983d91b9c03",
    "register_confirmed":	false
}