
POST http://localhost:8000/passenger HTTP/1.1
Content-Type:  application/json

{
    "name" : "rodolfo",
	"nickname" : "ro",
	"routeCode" : "aef88e44426a",
	"schoolName": "SESI teste",
	"monitorID" : "9744bdc1-106a-471f-aa41-3e78b338ab31"
}

###  BUSCAR TODOS PASSAGEIROS
GET  http://localhost:8000/passenger/ HTTP/1.1
Content-Type:  application/json

### BUSCAR POR ID
GET  http://localhost:8000/passenger/209b31f0-dce9-4405-ab59-c7844b7f91b5 HTTP/1.1
Content-Type:  application/json


### ATUALIZAR DADOS DO PASSAGEIROS
PUT   http://localhost:8000/passenger HTTP/1.1
Content-Type:  application/json

{
	"id": "893ea0fc-fdf2-4080-b566-6c3ad4efd54d",
	"name" : "GUILHERME",
	"nickname" : "GUI",
	"routeCode" : "cc724afccf12",
	"schoolName": "SESI 777",
	"goes":true,
	"comesback": true,
	"registerConfirmed": true,
	"monitorID": "d1b68cef-478c-43bb-a1e2-c1155305775f"
}

###

DELETE    http://localhost:8000/passenger/d7319148-5b13-49c1-a8c5-aa50856d503f HTTP/1.1
Content-Type:  application/json

### CONFIRMAR REGISTRO DO PASSAGEIRO
PUT   http://localhost:8000/passenger/confirm-passenger HTTP/1.1
Content-Type:  application/json

{
	"passengerID": 		"ce882581-1922-4cfb-8216-393f72a8ec0c",
    "registerConfirmed":	true
}


###
POST  http://localhost:8000/passenger/finalize-route HTTP/1.1
Content-Type:  application/json


###
GET  http://localhost:8000/passenger/not-confirmed/0397fe937858 HTTP/1.1
Content-Type:  application/json

###
GET  http://localhost:8000/passenger/list-passenger/52b4238b-8d54-4eb3-840b-7c05cf6e2eac HTTP/1.1
Content-Type:  application/json