version: '3'

services:
  # van:
  #   build: .
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - .:/app

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    tty: true
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vantracking
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306