DROP TABLE IF EXISTS drivers;
DROP TABLE IF EXISTS monitors;
DROP TABLE IF EXISTS partners;
DROP TABLE IF EXISTS passengers;
DROP TABLE IF EXISTS routes;
DROP TABLE IF EXISTS devices;
DROP TABLE IF EXISTS categories;
